### ISSUE TITLE
Why would a BytesMut decompose into multiple IoVecs?

### ISSUE THREAD

**Issue by mqudsi** [tokio-rs/bytes#304]
As I understand it, a `BytesMut` is necessarily backed by a contiguous allocation (and that's why it can be borrowed as a slice). Shouldn't that decompose into a single IoVec? 

In my case,

```rust
        let b1: &mut [u8] = &mut [0];
        let mut iovecs: [&mut IoVec; 1] = [b1.into()];

        // self.bytes is a BytesMut instance
        let mut buf = self.bytes.into_buf();
        // Is it really necessary to convert to a BufMut before being able to take ownership of the underlying bytes?
        let mut vec: Vec<u8> = unsafe {
            match buf.bytes_vec_mut(&mut iovecs) {
                1 => iovecs[0].to_owned(),
                // _ => Vec::new(),
                _ => panic!("Failed to get buffer!")
            }
        };
        debug_assert!(!buf.has_remaining());
```

I would expect (since the `BufMut` is created from a contiguously allocated `BytesMut`) the assertion to pass, i.e. a single call to `bytes_vec_mut()` with a slice one IoVec long consumes the entirety of the source `BytesMut`, but it is not (necessarily) the case in some cases where the original `BytesMut` has, e.g. 234 bytes remaining, I only get a dozen or so bytes out of it in the `IoVec`.

(Additionally, it is insanely confusing that `BytesMut.remaining_mut()/BytesMut.bytes_vec_mut(..)` returns one thing while `BytesMut.into_buf().remaining_mut()/BytesMut.into_buf().bytes_vec_mut()` returns another, e.g. the following passes:

```rust
        debug_assert!(self.bytes.remaining_mut() == 0);
        let mut buf = self.bytes.into_buf();
        debug_assert!(buf.remaining_mut() != 0);
```

I get why (one counts remaining free bytes available, the other counts total bytes not consumed) but the API is incredibly unergonomic.)

**Comment by seanmonstar** [comment]
There may be some confusion on what exactly each part of the API is supposed to be doing. Let me see if I can clarify:

- `BufMut::bytes_vec_mut` will try to put its writable bytes into a `&mut [&mut IoVec]`, but that doesn't mean the write index is *moved* yet. In order to move the write index, one needs to call `BufMut::advance_mut`.

  If you consider something like a `TcpStream`, in `read_buf`, it will create a list of `IoVec`s, pass it to the `BufMut` to fill, and then call `readv` on the socket. If there was no data available on the socket, then none of those bytes were filled.
- `BytesMut` as a `BufMut` gives access to the writable bytes (the bytes between `BytesMut::len()` and `BytesMut::capacity()`).
- Calling `BytesMut::into_buf()` will create a `Cursor<BytesMut>`. The purpose is to able to access `Cursor::position()..BytesMut::len()` as a `Buf`.
- It just so happens that `Cursor<impl AsMut<[u8]>>` can also be used as a `BufMut`, but the writable bytes *then* are `Cursor::position()..BytesMut::len()`.

-----

The `IntoBuf` stuff will be gone in v0.5, as `BytesMut` will just implement `Buf` and `BufMut` directly.

I also wonder if there may be an easier way to do what you want. Which is... what exactly do you want to do? After writing to a `BytesMut`, you wish to peel off those bytes?

**Comment by mqudsi** [comment]
Hi Sean, thanks for the reply.

My concern was actually that `BytesMut.into_buf().bytes_mut_vec()` returned a different range than the non-zero-copy `BytesMut.into_buf().collect()` did, as they should be strictly identical since the `BufMut` was formed from a single contiguous allocation.

However my test was faulty, and that is not the case.
