### ISSUE TITLE
How to safely turn a `&mut [std::mem::MaybeUninit<u8>]` into a `&mut [u8]`

### ISSUE THREAD

**Issue by little-dude** [tokio-rs/bytes#317]
Hello,

I'm trying to upgrade to the tokio master branch in prevision of the future release. `tokio_util::codec` uses the master branch of `bytes`, and I'm having difficulties to upgrade.

I have this piece of code:

```rust
impl<T> Encoder for NetlinkCodec<NetlinkMessage<T>>
where
    T: Debug + Eq + PartialEq + Clone + NetlinkSerializable<T>,
{
    type Item = NetlinkMessage<T>;
    type Error = io::Error;

    fn encode(&mut self, msg: Self::Item, buf: &mut BytesMut) -> Result<(), Self::Error> {
        let size = msg.buffer_len();
        unsafe {
            let bytes = buf.bytes_mut();
            if bytes.len() < size {
                return Err(io::Error::new(
                    io::ErrorKind::Other,
                    format!("message is {} bytes, but only {} bytes left in the buffer", size, bytes.len()),
                ));
            }
            // NetlinkMessage<T>::serialize takes a &mut [u8]
            msg.serialize(&mut buf.bytes_mut()[..size]);
            buf.advance_mut(size);
        }
        Ok(())
    }
}
```

Now, `bytes_mut()` returns a `&mut [MaybeUninit<u8>]` so this code fails with:

```
175 |             msg.serialize(&mut buf.bytes_mut()[..size]);
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found union `std::mem::MaybeUninit`
    |
    = note: expected type `&mut [u8]`
               found type `&mut [std::mem::MaybeUninit<u8>]`
```

The thing is I'm quite out of my depth, and I can't find out how to pass a `&mut [u8]` to my `serialize` method.

Is there a solution to this, or am I trying to do something that is just not possible?

**Comment by little-dude** [comment]
Oh I see that that `BytesMut` implements `AsMut<[u8]>`. Could I just use that to get a `&mut [u8]`,  and then call `advance_mut`?

**Comment by seanmonstar** [comment]
The `AsMut<[u8]>` section of `BytesMut` is the *already written-to* part, so that wouldn't be what you want.

You've got a few choices:

- The safest way to use to just the `put_*` methods from `BufMut`, if possible. Like `put_slice`, `put_u32`, etc.
- If you are about to write into the `u8`s, and are absolutely certain nothing will try to *read* it first, then it is defined behavior to transmute from `&mut [MaybeUninit<u8>]` to `&mut [u8]`, accord to the [layout guarantees of `MaybeUninit`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#layout).

  However, it looks like you're passing the slice to another trait. If user code can implement it, you can't really be sure they won't try to read from the slice before writing, which would be undefined behavior. In that case, you'd need to be sure to initialize that transmute slice *before* giving it to uncontrolled user code. Something like `for b in slice { *b = 0; }`.
- You pass the buck down the road, by just passing `&mut [MaybeUninit<u8>]` (or perhaps `&mut dyn BufMut` or something).

**Comment by little-dude** [comment]
Thanks a lot for laying out all the options I have @seanmonstar :)

I would definitely have gone for the transmute solution but as you said, I'm passing the slice to another trait.

So I'm still not sure which option I'll pick at the moment, but you answered all the questions I had so I'll close this. Thanks again!
