### ISSUE TITLE
Bytes lenght not set when receving from upd socket

### ISSUE THREAD

**Issue by morr0ne** [tokio-rs/bytes#446]
I'm trying to use bytes in conjunction with [tokio::net](https://docs.rs/tokio/0.3.4/tokio/net/)
When receiving from a [Udpsocket](https://docs.rs/tokio/0.3.4/tokio/net/struct.UdpSocket.html) using a BytesMut as the response object no len is set and the receiving bytes is always 0
```rust
let mut res = BytesMut::with_capacity(16);
let n = socket.recv(&mut res).await?;

assert_eq!(0,res.len());
assert_eq!(0,n);
```
I know for sure data is there because if I force it to a certain length I can easily read it
```rust
let mut res = BytesMut::with_capacity(16);
let n = socket.recv(&mut res).await?;
unsafe {
     res.set_len(16);
}

let data = res.get_i32();

println!("{}", data);
```

Either I'm doing something wrong or there is a bug in bytes because everything works fine if I just use a Vec\<u8\>
```rust
let mut res = vec![0; 16];
let n = socket.recv(&mut res).await?;

assert_eq!(16,res.len());
assert_eq!(16,n);
```

**Comment by Darksonn** [comment]
The problem is that your `BytesMut` is empty. When you give it to the [`UdpSocket::recv`][1] method, it is coerced into an empty slice, and the read is reported as empty as you didn't provide it anywhere to put the data. It works with the vector because the vector is not empty.

Your `set_len` call doesn't report data read from the `recv` call, rather it's just random uninitialized data that happened to be in memory where the `BytesMut` was allocated.
```rust
fn print_slice_len(slice: &mut[u8]) {
    println!("{}", slice.len());
}

fn main() {
    let mut res = BytesMut::with_capacity(16);
    print_slice_len(&mut res);
    
    let mut res = vec![0; 16];
    print_slice_len(&mut res);
}
```
```text
0
16
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ac61fc904979317b10d296ee6b7e0f7a)

[1]: https://docs.rs/tokio/0.3/tokio/net/struct.UdpSocket.html#method.recv

**Comment by morr0ne** [comment]
Thanks for the fast response, sorry if it's a stupid question but I'm new to rust. So I should first initialize BytesMut? How exactly do I do that?

**Comment by Darksonn** [comment]
This will work:
```rust
let mut res = BytesMut::with_capacity(16);
res.resize(16, 0);
let n = socket.recv(&mut res).await?;
```

**Comment by morr0ne** [comment]
Worked like a charm, thanks :D

**Comment by seanmonstar** [comment]
A side note: don't trust the `len` to know how many bytes were read, you need to check the integer returned by `recv` which tells you that. The buffer may have had 16 bytes of space, but only read 8 from the socket, for example.

**Comment by morr0ne** [comment]
What I ended up doing is the following
```rust
let mut announce_res = BytesMut::with_capacity(65508);
announce_res.resize(65508, 0);

let n = socket.recv(&mut announce_res).await?;
announce_res.truncate(n);
```

This is my first time working with bytes or UDP sockets. Thank you very much for the help :D
