### ISSUE TITLE
Saturate `at` in `split_to` and `split_off` methods, to avoid panic

### ISSUE THREAD

**Issue by k3d3** [tokio-rs/bytes#468]
Hello,

When working with `bytes`, I noticed that `split_to` panics if the `at` value is larger than or equal to the length: https://docs.rs/bytes/1.0.1/src/bytes/bytes.rs.html#401-423

I propose that this function be modified to remove the assert, and replace line 409:
```rust
if at == self.len() {
```

to instead be:
```rust
if at >= self.len() {
```

This would mean if you have a 5-byte `Bytes` struct and you called `.split_to(10)`, it would be as if you called `.split_to(5)` on it, i.e. it would return everything that's left. 

Additionally, this makes for properly-behaving code in release mode for any given `at` value.

I believe the change would be backwards-compatible for any non-panicking code.

Are there any objections to this change? If not, I could whip up a PR.

**Comment by k3d3** [comment]
I went ahead and created a PR for this: https://github.com/tokio-rs/bytes/pull/469

**Comment by vorner** [comment]
I'm not one of the maintainers, but I believe splitting out of bounds is panicking because std does the same thing.

https://doc.rust-lang.org/nightly/std/primitive.slice.html#panics-17

In general, I feel like these „auto-fixes“ might let a bug go unnoticed for longer than necessary. If you do a `split_to(10)`, you expect to have 10 bytes. You could even rely on that panic to protect some unsafe code accessing these 10 bytes, so in that sense, the change probably is not backwards compatible.

**Comment by seanmonstar** [comment]
I agree, I don't think this should be done. It's best to follow patterns in std, to surprise less people.

**Comment by k3d3** [comment]
That seems fair. I didn't realize this was a pattern that existed already in std. I still believe it's better to not have it panic, but I'll redirect my concerns elsewhere.

Thanks!
