### ISSUE TITLE
iter() is missing on Buf

### ISSUE THREAD

**Issue by matko** [tokio-rs/bytes#580]
The documentation for `IntoIter` claims that `Buf` should have an `iter()` function which will return an `IntoIter`. Unfortunately, this function seems to be missing, and nothing else provides similar functionality. Some types in the bytes crate do seem to have an `into_iter` which returns this type though (`Chain`, `Bytes` and `BytesMut`), but nothing seems to work on arbitrary `Buf` implementations.

I have my own `Buf` implementation and would very much like to iterate over it too. Unfortunately, as there is no generic `iter()` on `Buf`, and the constructor for `IntoIter` is only crate-public, I have no way to do this except by implementing my own iterator, even though `IntoIter` just does exactly what I want.

Is it possible to provide some way for me to make an `IntoIter` from an arbitrary `Buf` implementation?

**Comment by Darksonn** [comment]
Calling it `iter()` would be incorrect because it takes ownership. It should be called `.into_iter()`. However, adding a method to the `Buf` trait called `into_iter` is probably too much of a breaking change to do it at this point. It would make `byte_slice.into_iter()` fail with an error about it being ambiguous on the `&[u8]` type if you have `Buf` in scope.

I don't mind adding a constructor though.

**Comment by matko** [comment]
Making the existing constructor public instead of crate-public will work for me. If you like, I can do a PR for it.

Also, the documentation here will have to be modified: https://docs.rs/bytes/latest/bytes/buf/struct.IntoIter.html

**Comment by Darksonn** [comment]
Sure, I would be happy to merge a PR like that.
